### ISSUE TITLE
请问一下jsbsim.FGFDMExec的properties属性值有哪些是在哪里能够找到呢，方便告知吗。找遍了jsbsim的官网也没发现

### ISSUE THREAD

**Issue by Magqiao** [mrwangyou/DBRL#10]

**Comment by mrwangyou** [comment]
您好。

如果是想问关于空气动力学模型初始化部分的jsbsim.FGFDMExec()函数，或许可以看一下{JSBSim}/src/FGFDMExec.cpp文件。另外官网的手册中也能搜到[FGFDMExec相关的内容](https://jsbsim-team.github.io/jsbsim/classJSBSim_1_1FGFDMExec.html)

**Comment by Magqiao** [comment]
![image](https://github.com/mrwangyou/DBRL/assets/39947593/ce5124fd-41f9-413d-8f3b-4aa1e5a56b52)
想问一下的是像这里面的ic/lat-gc-deg这个属性的话是在哪里能找到呢

**Comment by mrwangyou** [comment]
> ![image](https://user-images.githubusercontent.com/39947593/273420701-ce5124fd-41f9-413d-8f3b-4aa1e5a56b52.png) 想问一下的是像这里面的ic/lat-gc-deg这个属性的话是在哪里能找到呢

JSBSim可以输入参数`--catalog`查询指定飞机的所有属性，也可以直接在`{JSBSim}/src/`中搜索需要的功能。

**Comment by Magqiao** [comment]
好的好的   感谢！！
