### ISSUE TITLE
场景Replay相关问题

### ISSUE THREAD

**Issue by WangKeji** [mrwangyou/DBRL#11]
作者你好！非常感谢你的分享。关于场景的回放我有一些疑惑。
+ 把render mode打开的话，训练开始后，dogfight软件界面内的视线会一直锁定在不飞的飞机上，反而是会另外生成一架飞机并进行起飞，但是现在我想把视角转移到实际飞行并训练的那架飞机上，观看他的飞行姿态，这个有办法实现吗？
+ 我观察到目前的gym环境采用的dogfight版本为1.0.2，dogfight在后续版本里给出了[Recorder API](https://github.com/harfang3d/dogfight-sandbox-hg2/tree/4f6d83ca0b463a1c0c243bc5746edd435d91e31c#recorder-api-overview)接口，我试着用Recorder去实现第一点里我想要的效果，但是没能成功，在Recorder模式下我的视角被锁定在了一架航母上。请问你有使用过后续版本的Recorder API吗？

**Comment by mrwangyou** [comment]
您好，感谢您对DBRL的关注。

对于Dogfight软件的疑问可以查看他们的官方页面，例如转移视角按1就可以实现，可见[链接](https://github.com/harfang3d/dogfight-sandbox-hg2#commons-views-commands)。目前我们还没有打算更新dogfight的版本，可能等整个仓库完善之后会去跟进这部分工作。此外，我们也完成了场景状态导出至可以直接用于TacView软件回放的功能，还没有详细测试过，感兴趣的话可以查看dev分支。

**Comment by WangKeji** [comment]
> 您好，感谢您对DBRL的关注。
> 
> 对于Dogfight软件的疑问可以查看他们的官方页面，例如转移视角按1就可以实现，可见[链接](https://github.com/harfang3d/dogfight-sandbox-hg2#commons-views-commands)。目前我们还没有打算更新dogfight的版本，可能等整个仓库完善之后会去跟进这部分工作。此外，我们也完成了场景状态导出至可以直接用于TacView软件回放的功能，还没有详细测试过，感兴趣的话可以查看dev分支。

感谢你们耐心且及时的回复！我会详细研读一下dev分支的。
