### ISSUE TITLE
你好，我想在GPU上运行这些代码，应该怎么去设置呢？

### ISSUE THREAD

**Issue by blah-a** [mrwangyou/DBRL#5]

**Comment by mrwangyou** [comment]
您好，感谢您对DBRL的关注。

如果您使用项目中的Stable Baselines3模型的话，只要正确安装了SB3，那么就会在GPU上运行。如果您计划使用PyTorch等自行实现深度强化学习算法，那么请按照Torch中的规则将数据和模型放入GPU进行训练。
