### ISSUE TITLE
您好，请问您使用的仿真平台是否支持修改想定？如将现有的2v2扩充到6v6，12v12等，来进行强化学习算法的训练？

### ISSUE THREAD

**Issue by kindle4367** [mrwangyou/DBRL#6]

**Comment by mrwangyou** [comment]
您好，感谢您对DBRL的关注。

根据JSBSim的联机写法，我推测是可以支持多智能体的，您可以尝试根据文档修改一下。Harfang环境是可以修改初始状态的，您只需要在文件中加入多架飞机即可。

**Comment by kindle4367** [comment]
非常感谢，我已经在https://github.com/harfang3d/dogfight-sandbox-hg2/issues/42 这个回答下找到了多智能体实现方法，现在能构建多个敌我智能体了
